project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - projects.qmd
      - teaching.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



